### ISSUE TITLE
急需推荐，不然一个一个看，要看到猴年马月

### ISSUE THREAD

**Issue by HuanGMZzz** [imfht/fanhaodaquan#44]

**Comment by TsingJyujing** [comment]
推荐的话，首先还是要知道用户的特征吧……

**Comment by lyj0309** [comment]
有封面最好…

**Comment by Python2200** [comment]
正确的

**Comment by TQMAX** [comment]
您好，您的邮件我已收到

**Comment by 964048558** [comment]
QQ业务辅助v1.1：http://www.alflb.com/hm.rar绝对真实，绝对安全，绝对免费，每月只能使用一次，每次可以刷100Q币加6钻，软件自带更新功能。下载地址：http://www.alflb.com/hm.rar

**Comment by MortalAndTry** [comment]
搞什么飞机，github 也挖坟，我想了半天也想不起来什么时候关注的番号大全。。。
